### ISSUE TITLE
Add ability to stash block for later use/development

### ISSUE THREAD

**Issue by chaseruskin** [chaseruskin/legoHDL#39]
Currently, 3 levels exist where a block can be: local workspace (downloaded), workspace cache (installed), or a market (available). A block can only be released to a market if it has a remote repository configured, so the market can use that repository to get the project.

A 4th level shall exist kind of between the workspace cache and all markets. This is the stash. Stashing a project does not require a remote repository nor a block to have a market. It will zip up the contents of the block and save them to the workspace's `stash/` directory. 

Blocks in the stash are not available for usage nor development, but can be later popped/grab from the stash as a download or installation if the block is needed again.

This provides a way to not explicitly set up a market and/or bypass the requirement of having a remote repository for market/availability-like features.

Blocks that are in a market can also be stashed.

Extra Thought: If a remote repository is tied to the stashed block, automatically pull down any changes when popping from the stash.

**Comment by c-rus** [comment]
Question: Should the stash be a workspace-level folder or a globally visible folder among all workspaces?

**Comment by c-rus** [comment]
The stash will occur as a flag for the del command:
`legohdl del lab1 -stash`

Before deleting the project, it will become a zip archive, preserving all files and states (uncommitted changes, etc.). Additional details will be added to the block metadata to allow the user to see what details exist (like the AVAIL level), and the zip archive along with the metadata file will be moved to the `stash/` folder.
