### ISSUE TITLE
Solve installation environment before installing blocks

### ISSUE THREAD

**Issue by chaseruskin** [chaseruskin/legoHDL#44]
Before just blindly installing blocks, make sure everything will work out as planned and prompt the user to "proceed?" on an installation. Solving an environment means to collect what packages will have to be installed, how much space will be used, and possibly what packages cannot be found/are missing, and what packages will be updated.

**Comment by c-rus** [comment]
Maybe use a `-force` flag to skip this process and just brute-force through the installation.
